import Foundation
import Combine

class LocalExerciseService {
    // Sample exercises to use when the API doesn't work
    private let sampleExercises: [Exercise] = [
        // Chest exercises
        Exercise(id: 51, uuid: "chest-1", name: "Bench Press", description: "Lie on a bench and press the barbell up.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 52, uuid: "chest-2", name: "Incline Dumbbell Press", description: "Lie on an incline bench and press the dumbbells up.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [3], language: 2, variations: nil, met: 4.5),
        Exercise(id: 53, uuid: "chest-3", name: "Decline Bench Press", description: "Lie on a decline bench and press the barbell up.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 54, uuid: "chest-4", name: "Cable Fly", description: "Stand between two cable machines and bring the handles together in front of your chest.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [2], language: 2, variations: nil, met: 4.0),
        Exercise(id: 55, uuid: "chest-5", name: "Push-Up", description: "Start in plank position and lower your body until your chest nearly touches the floor, then push back up.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [7], language: 2, variations: nil, met: 8.0),
        Exercise(id: 56, uuid: "chest-6", name: "Dumbbell Fly", description: "Lie on a bench with dumbbells in each hand, open your arms wide, then bring them together above your chest.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [3], language: 2, variations: nil, met: 4.5),
        Exercise(id: 57, uuid: "chest-7", name: "Pec Deck Machine", description: "Sit at a pec deck machine and bring the handles together in front of your chest.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [2], language: 2, variations: nil, met: 3.5),
        Exercise(id: 58, uuid: "chest-8", name: "Chest Dip", description: "Use parallel bars to lower your body by bending your elbows, then push back up.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [7], language: 2, variations: nil, met: 5.5),
        Exercise(id: 59, uuid: "chest-9", name: "Smith Machine Bench Press", description: "Lie on a bench under a Smith machine and press the bar up.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 60, uuid: "chest-10", name: "Incline Cable Fly", description: "Lie on an incline bench between two cable machines and bring the handles together above your chest.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [2], language: 2, variations: nil, met: 4.0),
        Exercise(id: 61, uuid: "chest-11", name: "Decline Dumbbell Press", description: "Lie on a decline bench and press the dumbbells up.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 62, uuid: "chest-12", name: "Machine Chest Press", description: "Sit at a chest press machine and press the handles forward.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [2], language: 2, variations: nil, met: 3.5),
        Exercise(id: 63, uuid: "chest-13", name: "Svend Press", description: "Stand with a weight plate between your hands and press it forward.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [7], language: 2, variations: nil, met: 4.0),
        Exercise(id: 64, uuid: "chest-14", name: "Landmine Press", description: "Press a barbell attached to a landmine attachment forward.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 65, uuid: "chest-15", name: "Resistance Band Chest Press", description: "Stand with a resistance band anchored behind you and press it forward.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [7], language: 2, variations: nil, met: 3.0),
        Exercise(id: 66, uuid: "chest-16", name: "Incline Smith Machine Press", description: "Lie on an incline bench under a Smith machine and press the bar up.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 67, uuid: "chest-17", name: "Dumbbell Pullover", description: "Lie on a bench with a dumbbell in both hands, lower the weight behind your head, then bring it back over your chest.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [3], language: 2, variations: nil, met: 4.5),
        Exercise(id: 68, uuid: "chest-18", name: "Cable Crossover", description: "Stand between two cable machines and bring the handles together in front of your chest.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [2], language: 2, variations: nil, met: 4.0),
        Exercise(id: 69, uuid: "chest-19", name: "Dumbbell Bench Press", description: "Lie on a bench with a dumbbell in each hand, lower the weights to your chest, then press them back up.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 70, uuid: "chest-20", name: "Push-Up with Elevated Feet", description: "Place your feet on an elevated surface and perform a push-up.", category: Exercise.Category(id: 1, name: "Chest"), muscles: [4], musclesSecondary: [2], equipment: [7], language: 2, variations: nil, met: 8.0),

        // Shoulder exercises
        Exercise(id: 71, uuid: "shoulder-1", name: "Shoulder Press", description: "Press the barbell overhead.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [3], equipment: [1], language: 2, variations: nil, met: 6.0),
        Exercise(id: 72, uuid: "shoulder-2", name: "Lateral Raise", description: "Raise the dumbbells to the side.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [3], language: 2, variations: nil, met: 3.5),
        Exercise(id: 73, uuid: "shoulder-3", name: "Front Raise", description: "Raise the dumbbells in front of you.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [3], language: 2, variations: nil, met: 3.5),
        Exercise(id: 74, uuid: "shoulder-4", name: "Reverse Fly", description: "Bend at the hips and raise the dumbbells to the side.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [3], language: 2, variations: nil, met: 4.0),
        Exercise(id: 75, uuid: "shoulder-5", name: "Arnold Press", description: "Press the dumbbells overhead while rotating your palms.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [3], equipment: [3], language: 2, variations: nil, met: 6.0),
        Exercise(id: 76, uuid: "shoulder-6", name: "Upright Row", description: "Pull the barbell up to your chest.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 77, uuid: "shoulder-7", name: "Face Pull", description: "Pull the cable towards your face.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [2], language: 2, variations: nil, met: 4.0),
        Exercise(id: 78, uuid: "shoulder-8", name: "Overhead Dumbbell Press", description: "Press the dumbbells overhead.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [3], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 79, uuid: "shoulder-9", name: "Seated Dumbbell Press", description: "Sit and press the dumbbells overhead.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [3], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 80, uuid: "shoulder-10", name: "Cable Lateral Raise", description: "Raise the cable to the side.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [2], language: 2, variations: nil, met: 3.5),
        Exercise(id: 81, uuid: "shoulder-11", name: "Dumbbell Shrug", description: "Shrug your shoulders with dumbbells in hand.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [3], language: 2, variations: nil, met: 4.0),
        Exercise(id: 82, uuid: "shoulder-12", name: "Smith Machine Shoulder Press", description: "Press the bar overhead on a Smith machine.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [3], equipment: [1], language: 2, variations: nil, met: 6.0),
        Exercise(id: 83, uuid: "shoulder-13", name: "Landmine Press", description: "Press a barbell attached to a landmine attachment forward.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [3], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 84, uuid: "shoulder-14", name: "Resistance Band Shoulder Press", description: "Press a resistance band overhead.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [3], equipment: [7], language: 2, variations: nil, met: 3.0),
        Exercise(id: 85, uuid: "shoulder-15", name: "Dumbbell Front Raise", description: "Raise the dumbbells in front of you.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [3], language: 2, variations: nil, met: 3.5),
        Exercise(id: 86, uuid: "shoulder-16", name: "Cable Face Pull", description: "Pull the cable towards your face.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [2], language: 2, variations: nil, met: 4.0),
        Exercise(id: 87, uuid: "shoulder-17", name: "Dumbbell Lateral Raise", description: "Raise the dumbbells to the side.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [3], language: 2, variations: nil, met: 3.5),
        Exercise(id: 88, uuid: "shoulder-18", name: "Machine Shoulder Press", description: "Sit at a shoulder press machine and press the handles overhead.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [3], equipment: [2], language: 2, variations: nil, met: 5.0),
        Exercise(id: 89, uuid: "shoulder-19", name: "Dumbbell Rear Delt Fly", description: "Bend at the hips and raise the dumbbells to the side.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [], equipment: [3], language: 2, variations: nil, met: 4.0),
        Exercise(id: 90, uuid: "shoulder-20", name: "Barbell Overhead Press", description: "Press the barbell overhead.", category: Exercise.Category(id: 5, name: "Shoulders"), muscles: [2], musclesSecondary: [3], equipment: [1], language: 2, variations: nil, met: 6.0),

        // Back exercises
        Exercise(id: 91, uuid: "back-1", name: "Pull-Up", description: "Pull yourself up on a bar.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [7], language: 2, variations: nil, met: 8.0),
        Exercise(id: 92, uuid: "back-2", name: "Bent Over Row", description: "Row the barbell towards your torso.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [1], language: 2, variations: nil, met: 6.0),
        Exercise(id: 93, uuid: "back-3", name: "Lat Pulldown", description: "Pull the bar down to your chest.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [2], language: 2, variations: nil, met: 5.0),
        Exercise(id: 94, uuid: "back-4", name: "Seated Cable Row", description: "Pull the cable handle towards your torso.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [2], language: 2, variations: nil, met: 4.5),
        Exercise(id: 95, uuid: "back-5", name: "T-Bar Row", description: "Row the bar towards your torso.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [1], language: 2, variations: nil, met: 6.0),
        Exercise(id: 96, uuid: "back-6", name: "Single Arm Dumbbell Row", description: "Row the dumbbell towards your torso.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 97, uuid: "back-7", name: "Inverted Row", description: "Pull your chest to the bar.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [7], language: 2, variations: nil, met: 4.0),
        Exercise(id: 98, uuid: "back-8", name: "Machine Row", description: "Sit at a rowing machine and pull the handles towards your torso.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [2], language: 2, variations: nil, met: 4.5),
        Exercise(id: 99, uuid: "back-9", name: "Barbell Deadlift", description: "Lift the barbell from the ground to hip level.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [1], language: 2, variations: nil, met: 7.0),
        Exercise(id: 100, uuid: "back-10", name: "Dumbbell Pullover", description: "Lie on a bench with a dumbbell in both hands, lower the weight behind your head, then bring it back over your chest.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [3], language: 2, variations: nil, met: 4.5),
        Exercise(id: 101, uuid: "back-11", name: "Reverse Grip Bent Over Row", description: "Row the barbell towards your torso with a reverse grip.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [1], language: 2, variations: nil, met: 6.0),
        Exercise(id: 102, uuid: "back-12", name: "Chin-Up", description: "Pull yourself up on a bar with palms facing you.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [7], language: 2, variations: nil, met: 8.0),
        Exercise(id: 103, uuid: "back-13", name: "Landmine Row", description: "Row the barbell towards your torso using a landmine attachment.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [1], language: 2, variations: nil, met: 5.5),
        Exercise(id: 104, uuid: "back-14", name: "Resistance Band Row", description: "Row the resistance band towards your torso.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [7], language: 2, variations: nil, met: 3.0),
        Exercise(id: 105, uuid: "back-15", name: "Smith Machine Row", description: "Row the bar towards your torso on a Smith machine.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 106, uuid: "back-16", name: "Cable Face Pull", description: "Pull the cable towards your face.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [2], language: 2, variations: nil, met: 4.0),
        Exercise(id: 107, uuid: "back-17", name: "Dumbbell Shrug", description: "Shrug your shoulders with dumbbells in hand.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [3], language: 2, variations: nil, met: 4.0),
        Exercise(id: 108, uuid: "back-18", name: "Barbell Shrug", description: "Shrug your shoulders with a barbell in hand.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 109, uuid: "back-19", name: "Dumbbell Rear Delt Fly", description: "Bend at the hips and raise the dumbbells to the side.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [3], language: 2, variations: nil, met: 4.0),
        Exercise(id: 110, uuid: "back-20", name: "Barbell Row", description: "Row the barbell towards your torso.", category: Exercise.Category(id: 3, name: "Back"), muscles: [12], musclesSecondary: [8], equipment: [1], language: 2, variations: nil, met: 6.0),

        // Glutes exercises
        Exercise(id: 111, uuid: "glutes-1", name: "Hip Thrust", description: "Thrust your hips upwards with a barbell.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [1], language: 2, variations: nil, met: 4.0),
        Exercise(id: 112, uuid: "glutes-2", name: "Glute Bridge", description: "Lift your hips off the ground.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [7], language: 2, variations: nil, met: 3.5),
        Exercise(id: 113, uuid: "glutes-3", name: "Cable Kickback", description: "Kick your leg back using a cable machine.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [2], language: 2, variations: nil, met: 4.0),
        Exercise(id: 114, uuid: "glutes-4", name: "Smith Machine Squat", description: "Squat down with a barbell on a Smith machine.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 115, uuid: "glutes-5", name: "Dumbbell Lunge", description: "Step forward with one leg and lower your body until both knees are bent at 90 degrees.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 116, uuid: "glutes-6", name: "Barbell Squat", description: "Squat down with a barbell on your back.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [1], language: 2, variations: nil, met: 6.0),
        Exercise(id: 117, uuid: "glutes-7", name: "Leg Press", description: "Press the platform away with your feet.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [2], language: 2, variations: nil, met: 4.5),
        Exercise(id: 118, uuid: "glutes-8", name: "Step-Up", description: "Step up onto a bench with one leg.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [7], language: 2, variations: nil, met: 4.0),
        Exercise(id: 119, uuid: "glutes-9", name: "Bulgarian Split Squat", description: "Place one foot on a bench behind you and squat down.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [7], language: 2, variations: nil, met: 5.0),
        Exercise(id: 120, uuid: "glutes-10", name: "Dumbbell Deadlift", description: "Stand with a dumbbell in each hand, bend at the hips and knees to lower the weights to the floor, then stand back up.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 121, uuid: "glutes-11", name: "Barbell Deadlift", description: "Lift the barbell from the ground to hip level.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [1], language: 2, variations: nil, met: 7.0),
        Exercise(id: 122, uuid: "glutes-12", name: "Kettlebell Swing", description: "Swing the kettlebell between your legs and up to shoulder height.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [7], language: 2, variations: nil, met: 6.0),
        Exercise(id: 123, uuid: "glutes-13", name: "Reverse Lunge", description: "Step back with one leg and lower your body until both knees are bent at 90 degrees.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [7], language: 2, variations: nil, met: 5.0),
        Exercise(id: 124, uuid: "glutes-14", name: "Single Leg Deadlift", description: "Stand on one leg and lower the dumbbells to the floor.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 125, uuid: "glutes-15", name: "Hip Abduction Machine", description: "Sit at a hip abduction machine and push the pads apart.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [2], language: 2, variations: nil, met: 3.5),
        Exercise(id: 126, uuid: "glutes-16", name: "Glute Ham Raise", description: "Raise your body using your glutes and hamstrings.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [2], language: 2, variations: nil, met: 4.5),
        Exercise(id: 127, uuid: "glutes-17", name: "Smith Machine Lunge", description: "Lunge forward with a barbell on a Smith machine.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 128, uuid: "glutes-18", name: "Resistance Band Kickback", description: "Kick your leg back using a resistance band.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [7], language: 2, variations: nil, met: 3.0),
        Exercise(id: 129, uuid: "glutes-19", name: "Dumbbell Step-Up", description: "Step up onto a bench with a dumbbell in each hand.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [3], language: 2, variations: nil, met: 4.0),
        Exercise(id: 130, uuid: "glutes-20", name: "Barbell Hip Thrust", description: "Thrust your hips upwards with a barbell.", category: Exercise.Category(id: 7, name: "Glutes"), muscles: [8], musclesSecondary: [10], equipment: [1], language: 2, variations: nil, met: 4.0),

        // Legs exercises
        Exercise(id: 131, uuid: "legs-1", name: "Squat", description: "Lower your body by bending your knees.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [1], language: 2, variations: nil, met: 6.0),
        Exercise(id: 132, uuid: "legs-2", name: "Leg Press", description: "Press the platform away with your feet.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [2], language: 2, variations: nil, met: 4.5),
        Exercise(id: 133, uuid: "legs-3", name: "Lunge", description: "Step forward with one leg and lower your body until both knees are bent at 90 degrees.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [7], language: 2, variations: nil, met: 5.0),
        Exercise(id: 134, uuid: "legs-4", name: "Leg Curl", description: "Lie face down on a leg curl machine and curl your legs towards your buttocks.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [11], musclesSecondary: [10], equipment: [2], language: 2, variations: nil, met: 3.5),
        Exercise(id: 135, uuid: "legs-5", name: "Calf Raise", description: "Stand on a step with your heels hanging off and raise your heels as high as possible.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [13], musclesSecondary: [], equipment: [7], language: 2, variations: nil, met: 3.0),
        Exercise(id: 136, uuid: "legs-6", name: "Dumbbell Squat", description: "Stand with a dumbbell in each hand and lower your body as if sitting down.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 137, uuid: "legs-7", name: "Dumbbell Lunge", description: "Step forward with one leg and lower your body until both knees are bent at 90 degrees.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 138, uuid: "legs-8", name: "Leg Extension", description: "Sit on a leg extension machine and extend your legs out in front of you.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [], equipment: [2], language: 2, variations: nil, met: 3.5),
        Exercise(id: 139, uuid: "legs-9", name: "Barbell Squat", description: "Lower your body by bending your knees with a barbell on your back.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [1], language: 2, variations: nil, met: 6.0),
        Exercise(id: 140, uuid: "legs-10", name: "Smith Machine Squat", description: "Lower your body by bending your knees on a Smith machine.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 141, uuid: "legs-11", name: "Leg Press Machine", description: "Press the platform away with your feet on a leg press machine.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [2], language: 2, variations: nil, met: 4.5),
        Exercise(id: 142, uuid: "legs-12", name: "Dumbbell Step-Up", description: "Step up onto a bench with a dumbbell in each hand.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [3], language: 2, variations: nil, met: 4.0),
        Exercise(id: 143, uuid: "legs-13", name: "Bulgarian Split Squat", description: "Place one foot on a bench behind you and squat down.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [7], language: 2, variations: nil, met: 5.0),
        Exercise(id: 144, uuid: "legs-14", name: "Dumbbell Calf Raise", description: "Stand on a step with a dumbbell in each hand and raise your heels as high as possible.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [13], musclesSecondary: [], equipment: [3], language: 2, variations: nil, met: 3.0),
        Exercise(id: 145, uuid: "legs-15", name: "Barbell Lunge", description: "Step forward with one leg and lower your body until both knees are bent at 90 degrees with a barbell on your back.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [1], language: 2, variations: nil, met: 5.0),
        Exercise(id: 146, uuid: "legs-16", name: "Leg Curl Machine", description: "Lie face down on a leg curl machine and curl your legs towards your buttocks.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [11], musclesSecondary: [10], equipment: [2], language: 2, variations: nil, met: 3.5),
        Exercise(id: 147, uuid: "legs-17", name: "Dumbbell Lunge", description: "Step forward with one leg and lower your body until both knees are bent at 90 degrees.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 148, uuid: "legs-18", name: "Barbell Deadlift", description: "Lift the barbell from the ground to hip level.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [1], language: 2, variations: nil, met: 7.0),
        Exercise(id: 149, uuid: "legs-19", name: "Dumbbell Deadlift", description: "Stand with a dumbbell in each hand, bend at the hips and knees to lower the weights to the floor, then stand back up.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [11], equipment: [3], language: 2, variations: nil, met: 5.0),
        Exercise(id: 150, uuid: "legs-20", name: "Leg Extension Machine", description: "Sit on a leg extension machine and extend your legs out in front of you.", category: Exercise.Category(id: 2, name: "Legs"), muscles: [10], musclesSecondary: [], equipment: [2], language: 2, variations: nil, met: 3.5),

        // Stomach exercises
        Exercise(id: 151, uuid: "stomach-1", name: "Crunch", description: "Curl your shoulders towards your pelvis.", category: Exercise.Category(id: 6, name: "Abs"), muscles: [6], musclesSecondary: [], equipment: [7], language: 2, variations: nil, met: 3.0),
        Exercise(id: 152, uuid: "stomach-2", name: "Plank", description: "Hold a plank position.", category: Exercise.Category(id: 6, name: "Abs"), muscles: [6], musclesSecondary: [], equipment: [7], language: 2, variations: nil, met: 3.0),
        Exercise(id: 153, uuid: "stomach-3", name: "Russian Twist", description: "Sit on the floor with a dumbbell in both hands, twist your torso to one side, then the other.", category: Exercise.Category(id: 6, name: "Abs"), muscles: [6], musclesSecondary: [8], equipment: [3], language: 2, variations: nil, met: 4.0),
        Exercise(id: 154, uuid: "stomach-4", name: "Leg Raise", description: "Lie on your back and raise your legs towards the ceiling.", category: Exercise.Category(id: 6, name: "Abs"), muscles: [6], musclesSecondary: [], equipment: [7], language: 2, variations: nil, met: 3.5),
        Exercise(id: 155, uuid: "stomach-5", name: "Bicycle Crunch", description: "Lie on your back and pedal your legs in the air while touching your elbows to the opposite knee.", category: Exercise.Category(id: 6, name: "Abs"), muscles: [6], musclesSecondary: [], equipment: [7], language: 2, variations: nil, met: 3.5),
        Exercise(id: 156, uuid: "stomach-6", name: "Hanging Leg Raise", description: "Hang from a bar and raise your legs towards your chest.", category: Exercise.Category(id: 6, name: "Abs"), muscles: [6], musclesSecondary: [], equipment: [7], language: 2, variations: nil, met: 4.0),
        Exercise(id: 157, uuid: "stomach-7", name: "Cable Crunch", description: "Kneel in front of a cable machine and crunch your torso down.", category: Exercise.Category(id: 6, name: "Abs"), muscles: [6], musclesSecondary: [], equipment: [2], language: 2, variations: nil, met: 3.5),
        Exercise(id: 158, uuid: "stomach-8", name: "Ab Wheel Rollout", description: "Kneel on the floor and roll an ab wheel forward and back.", category: Exercise.Category(id: 6, name: "Abs"), muscles: [6], musclesSecondary: [], equipment: [7], language: 2, variations: nil, met: 4.0),
        Exercise(id: 159, uuid: "stomach-9", name: "Side Plank", description: "Lie on your side and lift your body off the ground, supporting yourself on one forearm.", category: Exercise.Category(id: 6, name: "Abs"), muscles: [6], musclesSecondary: [], equipment: [7], language: 2, variations: nil, met: 3.0),
        Exercise(id: 160, uuid: "stomach-10", name: "Mountain Climbers", description: "Start in a plank position and alternate bringing your knees to your chest.", category: Exercise.Category(id: 6, name: "Abs"), muscles: [6], musclesSecondary: [], equipment: [7], language: 2, variations: nil, met: 4.0)
    ]
    
    // Function to get all sample exercises
    func fetchExercises() -> AnyPublisher<ExerciseResult, Error> {
        return Just(ExerciseResult(exercises: sampleExercises, nextPage: nil))
            .setFailureType(to: Error.self)
            .eraseToAnyPublisher()
    }
    
    // Function to get filtered exercises based on search
    func searchExercises(query: String) -> AnyPublisher<ExerciseResult, Error> {
        let filteredExercises = sampleExercises.filter { 
            $0.name.localizedCaseInsensitiveContains(query) || 
            ($0.description?.localizedCaseInsensitiveContains(query) ?? false)
        }
        
        return Just(ExerciseResult(exercises: filteredExercises, nextPage: nil))
            .setFailureType(to: Error.self)
            .eraseToAnyPublisher()
    }
} 